name: 20 SCA

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-22.04" ]
        manifest_file: [ "pom.xml" ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    name: SCA Java project
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Snyk SCA Scan
        uses: snyk/actions/maven@v3
        continue-on-error: true
        with:
          args: test --all-projects --json-file-output=snyk-report.json --sarif-file-output=snyk-report.sarif
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}

      - name: Print JSON analysis report
        if: always()
        run: cat snyk-report.json

      - name: Print SARIF analysis report
        if: always()
        run: cat snyk-report.sarif