name: 20 SCA

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-22.04" ]
        manifest_file: [ "pom.xml" ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    name: SCA Java project
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      
      - name: Fix mvnw permissions
        run: chmod +x ./mvnw
      - name: Snyk SCA Scan
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2.21.2
        with:
          sarif_file: snyk.sarif

      #- name: Print JSON analysis report
      #  if: always()
      #  run: cat snyk-report.json

      - name: Print SARIF analysis report
        if: always()
        run: cat snyk.sarif